services:
  placement:
    image: "daprio/dapr:${DAPR_VERSION:-1.11.6}"
    command:
      [
        "./placement",
        "--log-level",
        "debug",
        "--port",
        "50005"
      ]
    ports:
      - "50005:50005"
    networks:
      - daprnet
  cron-issue-sample:
    image: "ko.local/m-moris/dapr-cron-issue/main:latest"
    environment:
      - ZZZ_SLEEP=${ZZZ_SLEEP:-10s}
    networks:
      - daprnet
  daprd:
    image: "daprio/daprd:${DAPR_VERSION:-1.11.6}"
    depends_on:
      - cron-issue-sample
    command:
      [
        "./daprd",
        "--app-id",
        "moris-cron-sample",
        "--app-protocol",
        "grpc",
        "--dapr-grpc-port",
        "50001",
        "--app-port",
        "51051",
        "--placement-host-address",
        "placement:50005", # Dapr's placement service can be reach via the docker DNS entry
        "--components-path",
        "/config"
      ]
    volumes:
      - ./config-docker:/config
    network_mode: "service:cron-issue-sample" # Attach the nodeapp-dapr service to the nodeapp network namespace

networks:
  daprnet:
    driver: bridge
    external: true