# https://docs.dapr.io/reference/resource-specs/component-schema/
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: h2-binding
spec:
  type: bindings.cron
  version: v1
  initTimeout: 30s
  ignoreErrors: false
  metadata:
  - name: schedule
    value: "@every 1s"
